/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Database.ConnectOracle;
import View.Login;

import java.awt.Window;

import static View.Menu.logoutUser;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hao
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    Connection con;
    Statement stmt;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        LB_PGA = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        LB_SESSION = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        tab3 = new javax.swing.JPanel();
        LB_SGA = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        LB_PROCESS = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        LB_INSTANCE = new javax.swing.JLabel();
        tab6 = new javax.swing.JPanel();
        LB_DATABASE = new javax.swing.JLabel();
        tab8 = new javax.swing.JPanel();
        LB_DATAFILE = new javax.swing.JLabel();
        tab11 = new javax.swing.JPanel();
        LB_CONTROLFILE = new javax.swing.JLabel();
        tab12 = new javax.swing.JPanel();
        LB_SPFILE = new javax.swing.JLabel();
        tab7 = new javax.swing.JPanel();
        LB_AUDIT = new javax.swing.JLabel();

        btnDXM = new javax.swing.JButton();

        jPanel2 = new javax.swing.JPanel();
        Panel_Session = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_SESSION = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_session = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txt_SID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Txt_SERIAL = new javax.swing.JTextField();
        HUY_SESSION = new javax.swing.JButton();
        Panel_Sga = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBL_SGA = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        Panel_Pga = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        TBL_PGA = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        Panel_Process = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TBL_PROCESS = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        Panel_Instance = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TBL_INSTANCE = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        Panel_Database = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        TBL_DATABASE = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        Panel_Datafile = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        TBL_DATAFILE = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        Panel_ControlFile = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        TBL_CONTROLFILE = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        Panel_SpFile = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        TBL_SPFILE = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        Panel_Audit = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        TBL_AUDIT = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        Combobox_UserName = new javax.swing.JComboBox<>();
        Button_Loc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(191, 658));

        tab1.setBackground(new java.awt.Color(204, 204, 204));

        LB_PGA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_PGA.setText("PGA");
        LB_PGA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_PGAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_PGA)
                .addGap(68, 68, 68))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_PGA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab2.setBackground(new java.awt.Color(204, 204, 204));

        LB_SESSION.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_SESSION.setText("SESSION");
        LB_SESSION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_SESSIONMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(LB_SESSION)
                .addGap(43, 43, 43))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addComponent(LB_SESSION)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manager");


        tab3.setBackground(new java.awt.Color(204, 204, 204));

        LB_SGA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_SGA.setText("SGA");
        LB_SGA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_SGAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_SGA)
                .addGap(70, 70, 70))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_SGA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab4.setBackground(new java.awt.Color(204, 204, 204));

        LB_PROCESS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_PROCESS.setText("PROCESS");
        LB_PROCESS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_PROCESSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_PROCESS)
                .addGap(42, 42, 42))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_PROCESS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab5.setBackground(new java.awt.Color(204, 204, 204));

        LB_INSTANCE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_INSTANCE.setText("INSTANCE");
        LB_INSTANCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_INSTANCEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_INSTANCE)
                .addGap(34, 34, 34))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_INSTANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab6.setBackground(new java.awt.Color(204, 204, 204));

        LB_DATABASE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_DATABASE.setText(" DATABASE");
        LB_DATABASE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_DATABASEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab6Layout = new javax.swing.GroupLayout(tab6);
        tab6.setLayout(tab6Layout);
        tab6Layout.setHorizontalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_DATABASE)
                .addGap(28, 28, 28))
        );
        tab6Layout.setVerticalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_DATABASE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab8.setBackground(new java.awt.Color(204, 204, 204));

        LB_DATAFILE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_DATAFILE.setText(" DATAFILE");
        LB_DATAFILE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_DATAFILEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab8Layout = new javax.swing.GroupLayout(tab8);
        tab8.setLayout(tab8Layout);
        tab8Layout.setHorizontalGroup(
            tab8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_DATAFILE)
                .addGap(34, 34, 34))
        );
        tab8Layout.setVerticalGroup(
            tab8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_DATAFILE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab11.setBackground(new java.awt.Color(204, 204, 204));

        LB_CONTROLFILE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_CONTROLFILE.setText("CONTROLFILE");
        LB_CONTROLFILE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_CONTROLFILEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab11Layout = new javax.swing.GroupLayout(tab11);
        tab11.setLayout(tab11Layout);
        tab11Layout.setHorizontalGroup(
            tab11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab11Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(LB_CONTROLFILE)
                .addGap(14, 14, 14))
        );
        tab11Layout.setVerticalGroup(
            tab11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_CONTROLFILE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab12.setBackground(new java.awt.Color(204, 204, 204));

        LB_SPFILE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_SPFILE.setText("SPFILE");
        LB_SPFILE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_SPFILEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab12Layout = new javax.swing.GroupLayout(tab12);
        tab12.setLayout(tab12Layout);
        tab12Layout.setHorizontalGroup(
            tab12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_SPFILE)
                .addGap(54, 54, 54))
        );
        tab12Layout.setVerticalGroup(
            tab12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_SPFILE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab7.setBackground(new java.awt.Color(204, 204, 204));

        LB_AUDIT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB_AUDIT.setText("AUDIT");
        LB_AUDIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_AUDITMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab7Layout = new javax.swing.GroupLayout(tab7);
        tab7.setLayout(tab7Layout);
        tab7Layout.setHorizontalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_AUDIT)
                .addGap(53, 53, 53))
        );
        tab7Layout.setVerticalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab7Layout.createSequentialGroup()
                .addComponent(LB_AUDIT)
                .addGap(0, 0, Short.MAX_VALUE))
        );


        btnDXM.setText("Đăng xuất");
        btnDXM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDXMActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))

            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnDXM, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))

        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))

                .addGap(30, 30, 30)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(btnDXM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))

        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(620, 642));

        Panel_Session.setBackground(new java.awt.Color(204, 204, 204));

        TBL_SESSION.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "SERIAL#", "USERNAME", "PROGRAM"
            }
        ));
        TBL_SESSION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_SESSIONMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_SESSION);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Thông tin các session");

        jLabel5.setText("Số session");

        jLabel6.setText("SID");

        Txt_SID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_SIDActionPerformed(evt);
            }
        });

        jLabel7.setText("SERIAL#");

        Txt_SERIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_SERIALActionPerformed(evt);
            }
        });

        HUY_SESSION.setText("Hủy Sesion");
        HUY_SESSION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HUY_SESSIONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_SessionLayout = new javax.swing.GroupLayout(Panel_Session);
        Panel_Session.setLayout(Panel_SessionLayout);
        Panel_SessionLayout.setHorizontalGroup(
            Panel_SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SessionLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(Panel_SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(Panel_SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_SERIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_SID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(HUY_SESSION)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Panel_SessionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SessionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SessionLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SessionLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(label_session)
                .addGap(147, 147, 147))
        );
        Panel_SessionLayout.setVerticalGroup(
            Panel_SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SessionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_session))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel_SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_SessionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Panel_SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Txt_SID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Txt_SERIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_SessionLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(HUY_SESSION)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        Panel_Sga.setBackground(new java.awt.Color(204, 204, 204));

        TBL_SGA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "VALUE", "CON_ID"
            }
        ));
        jScrollPane2.setViewportView(TBL_SGA);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("SGA");

        javax.swing.GroupLayout Panel_SgaLayout = new javax.swing.GroupLayout(Panel_Sga);
        Panel_Sga.setLayout(Panel_SgaLayout);
        Panel_SgaLayout.setHorizontalGroup(
            Panel_SgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SgaLayout.createSequentialGroup()
                .addGroup(Panel_SgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_SgaLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_SgaLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        Panel_SgaLayout.setVerticalGroup(
            Panel_SgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SgaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        Panel_Pga.setBackground(new java.awt.Color(204, 204, 204));

        TBL_PGA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "VALUE", "UNIT", "CON_ID"
            }
        ));
        jScrollPane11.setViewportView(TBL_PGA);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("PGA");

        javax.swing.GroupLayout Panel_PgaLayout = new javax.swing.GroupLayout(Panel_Pga);
        Panel_Pga.setLayout(Panel_PgaLayout);
        Panel_PgaLayout.setHorizontalGroup(
            Panel_PgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PgaLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PgaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(274, 274, 274))
        );
        Panel_PgaLayout.setVerticalGroup(
            Panel_PgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PgaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        Panel_Process.setBackground(new java.awt.Color(204, 204, 204));

        TBL_PROCESS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SPID", "USERNAME", "PROGRAM"
            }
        ));
        jScrollPane10.setViewportView(TBL_PROCESS);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("PROCESS");

        javax.swing.GroupLayout Panel_ProcessLayout = new javax.swing.GroupLayout(Panel_Process);
        Panel_Process.setLayout(Panel_ProcessLayout);
        Panel_ProcessLayout.setHorizontalGroup(
            Panel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProcessLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(Panel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ProcessLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ProcessLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(243, 243, 243))))
        );
        Panel_ProcessLayout.setVerticalGroup(
            Panel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProcessLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        Panel_Instance.setBackground(new java.awt.Color(204, 204, 204));

        TBL_INSTANCE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "INSTANCE_NAME", "HOST_NAME", "STARTUP_TIME"
            }
        ));
        jScrollPane12.setViewportView(TBL_INSTANCE);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("INSTANCE");

        javax.swing.GroupLayout Panel_InstanceLayout = new javax.swing.GroupLayout(Panel_Instance);
        Panel_Instance.setLayout(Panel_InstanceLayout);
        Panel_InstanceLayout.setHorizontalGroup(
            Panel_InstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InstanceLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_InstanceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(244, 244, 244))
        );
        Panel_InstanceLayout.setVerticalGroup(
            Panel_InstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_InstanceLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        Panel_Database.setBackground(new java.awt.Color(204, 204, 204));

        TBL_DATABASE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "LOG_MODE", "OPEN_MODE"
            }
        ));
        jScrollPane13.setViewportView(TBL_DATABASE);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setText("DATABASE");

        javax.swing.GroupLayout Panel_DatabaseLayout = new javax.swing.GroupLayout(Panel_Database);
        Panel_Database.setLayout(Panel_DatabaseLayout);
        Panel_DatabaseLayout.setHorizontalGroup(
            Panel_DatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DatabaseLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DatabaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(245, 245, 245))
        );
        Panel_DatabaseLayout.setVerticalGroup(
            Panel_DatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DatabaseLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Panel_Datafile.setBackground(new java.awt.Color(204, 204, 204));

        TBL_DATAFILE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "FILE_NAME", "TABLESPACE_NAME", "BYTES"
            }
        ));
        jScrollPane15.setViewportView(TBL_DATAFILE);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("DATAFILE");

        javax.swing.GroupLayout Panel_DatafileLayout = new javax.swing.GroupLayout(Panel_Datafile);
        Panel_Datafile.setLayout(Panel_DatafileLayout);
        Panel_DatafileLayout.setHorizontalGroup(
            Panel_DatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DatafileLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(Panel_DatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DatafileLayout.createSequentialGroup()
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DatafileLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(236, 236, 236))))
        );
        Panel_DatafileLayout.setVerticalGroup(
            Panel_DatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DatafileLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        Panel_ControlFile.setBackground(new java.awt.Color(204, 204, 204));

        TBL_CONTROLFILE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "STATUS", "IS_RECOVERY_DEST_FILE"
            }
        ));
        jScrollPane16.setViewportView(TBL_CONTROLFILE);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText("CONTROL FILE");

        javax.swing.GroupLayout Panel_ControlFileLayout = new javax.swing.GroupLayout(Panel_ControlFile);
        Panel_ControlFile.setLayout(Panel_ControlFileLayout);
        Panel_ControlFileLayout.setHorizontalGroup(
            Panel_ControlFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ControlFileLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(Panel_ControlFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ControlFileLayout.createSequentialGroup()
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ControlFileLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(217, 217, 217))))
        );
        Panel_ControlFileLayout.setVerticalGroup(
            Panel_ControlFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ControlFileLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        Panel_SpFile.setBackground(new java.awt.Color(204, 204, 204));

        TBL_SPFILE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUM", "NAME", "VALUE"
            }
        ));
        jScrollPane14.setViewportView(TBL_SPFILE);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setText("SPFILE");

        javax.swing.GroupLayout Panel_SpFileLayout = new javax.swing.GroupLayout(Panel_SpFile);
        Panel_SpFile.setLayout(Panel_SpFileLayout);
        Panel_SpFileLayout.setHorizontalGroup(
            Panel_SpFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SpFileLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(Panel_SpFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SpFileLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SpFileLayout.createSequentialGroup()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        Panel_SpFileLayout.setVerticalGroup(
            Panel_SpFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SpFileLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        Panel_Audit.setBackground(new java.awt.Color(204, 204, 204));

        TBL_AUDIT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SESSION_ID", "DB_USER", "OS_USER", "EXTENDED_TIMESTAMP", "OBJECT_SCHEMA", "OBJECT_NAME", "STATEMENT_TYPE", "SQL_TEXT"
            }
        ));
        jScrollPane17.setViewportView(TBL_AUDIT);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setText("Báo cáo Audit");

        Button_Loc.setText("Lọc");
        Button_Loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_AuditLayout = new javax.swing.GroupLayout(Panel_Audit);
        Panel_Audit.setLayout(Panel_AuditLayout);
        Panel_AuditLayout.setHorizontalGroup(
            Panel_AuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AuditLayout.createSequentialGroup()
                .addGroup(Panel_AuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AuditLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel21))
                    .addGroup(Panel_AuditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_AuditLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(Combobox_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Button_Loc)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Panel_AuditLayout.setVerticalGroup(
            Panel_AuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AuditLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(Panel_AuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combobox_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Loc))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Panel_SpFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(Panel_Session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel_Sga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(Panel_Pga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 72, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Process, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(163, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Instance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Database, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(161, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Datafile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(168, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_ControlFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Audit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_SpFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(Panel_Session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(Panel_Sga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 15, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(Panel_Pga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(Panel_Process, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 15, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Instance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Database, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Datafile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_ControlFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Audit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 626, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(196, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Biến lưu trạng thái session
    private String sessionID;

    public String getSessionID() {
        return sessionID;
    }
// Setter cho sessionID

    public void setSessionID(String sessionID) {
        this.sessionID = sessionID;
    }

// Phương thức để tìm và đóng form thuộc session tương ứng
    private void closeFormBySessionID(String sessionID) {
    for (Window window : Window.getWindows()) {
        if (window instanceof JFrame) {
            JFrame frame = (JFrame) window;
            // Kiểm tra trạng thái session của form
            // Nếu trùng với sessionID cần đóng, thực hiện đóng form
            if (frame.isVisible() && frame instanceof Manager) {
                Manager manager = (Manager) frame;
                String formSessionID = manager.getSessionID();
                if (formSessionID != null && formSessionID.equals(sessionID)) {
                    frame.dispose();
                    
                    // Kiểm tra nếu form hiện tại là form Manager
                    if (frame instanceof Manager) {
                        // Quay lại form đăng ký
                        Login login = new Login();
                        login.setVisible(true);
                    }
                    
                    break;
                }
            }
        }
    }
}

    public void getDataTable_SGA() throws ClassNotFoundException, SQLException {
        try {
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT Name,value,con_id FROM V$SGA";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_SGA.getModel();
            model.setRowCount(0)
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("NAME"),
                    rs.getBigDecimal("VALUE"),
                    rs.getBigDecimal("CON_ID")

                });
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    public void getDataTable_PGA() throws ClassNotFoundException, SQLException {
        try {
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT Name,value,unit,con_id FROM V$PGASTAT";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_PGA.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("NAME"),
                    rs.getBigDecimal("VALUE"),
                    rs.getString("UNIT"),
                    rs.getBigDecimal("CON_ID")

                });
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    public void getDataTable_PROCESS() throws ClassNotFoundException, SQLException {
        try {
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT SPID, USERNAME, PROGRAM FROM V$PROCESS";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_PROCESS.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("SPID"),
                    rs.getString("USERNAME"),
                    rs.getString("PROGRAM")

                });
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    public void getDataTable_INSTANCE() throws ClassNotFoundException, SQLException {
        try {
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT INSTANCE_NAME, HOST_NAME, STARTUP_TIME FROM V$INSTANCE";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_INSTANCE.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("INSTANCE_NAME"),
                    rs.getString("HOST_NAME"),
                    rs.getTimestamp("STARTUP_TIME"),});
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    public void getDataTable_DATABASE() throws ClassNotFoundException, SQLException {
        try {
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT NAME, LOG_MODE, OPEN_MODE FROM V$DATABASE";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_DATABASE.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("NAME"),
                    rs.getString("LOG_MODE"),
                    rs.getString("OPEN_MODE"),});
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    public void getDataTable_DATAFILE() throws ClassNotFoundException, SQLException {
        try {
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT FILE_NAME, TABLESPACE_NAME, BYTES FROM DBA_DATA_FILES";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_DATAFILE.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("FILE_NAME"),
                    rs.getString("TABLESPACE_NAME"),
                    rs.getBigDecimal("BYTES")
                });
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    public void getDataTable_CONTROLFILE() throws ClassNotFoundException, SQLException {
        try {
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT NAME, STATUS, IS_RECOVERY_DEST_FILE FROM V$CONTROLFILE";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_CONTROLFILE.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("NAME"),
                    rs.getString("STATUS"),
                    rs.getString("IS_RECOVERY_DEST_FILE")
                });
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    public void getDataTable_SPFILE() throws ClassNotFoundException, SQLException {
        try {
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT NUM,NAME,VALUE FROM V$PARAMETER WHERE NAME = 'spfile'";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_SPFILE.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getBigDecimal("NUM"),
                    rs.getString("NAME"),
                    rs.getString("VALUE")
                });
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    public void getDataTable_SESSION() throws ClassNotFoundException, SQLException {
        try {
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT sid,serial#,username,program FROM V$SESSION WHERE TYPE!='BACKGROUP'";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_SESSION.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getBigDecimal("SID"),
                    rs.getBigDecimal("SERIAL#"),
                    rs.getString("USERNAME"),
                    rs.getString("PROGRAM")
                });
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    public void getDataText_SESSION() throws ClassNotFoundException, SQLException {
        int count = 0;
        try {
//            String tk = Login.getDataUser.tenTk;
//            String mk = Login.getDataUser.mk;
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT COUNT(*) AS session_count FROM V$SESSION";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);

            if (rs.next()) { // Di chuyển con trỏ của ResultSet
                count = rs.getInt("session_count");
                label_session.setText(String.valueOf(count));
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        } finally {
            // Đảm bảo đóng tài nguyên
            if (rs != null) {
                rs.close();
            }
            if (stmt != null) {
                stmt.close();
            }
            if (con != null) {
                con.close();
            }
        }
    }

    public void getDataTable_AUDIT() throws ClassNotFoundException, SQLException {
        try {
//            String tk = Login.getDataUser.tenTk;
//            String mk = Login.getDataUser.mk;
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT session_id,db_user,os_user,extended_timestamp,object_schema,object_name,statement_type,sql_text FROM dba_fga_audit_trail";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_AUDIT.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getBigDecimal("SESSION_ID"),
                    rs.getString("DB_USER"),
                    rs.getString("OS_USER"),
                    rs.getTimestamp("EXTENDED_TIMESTAMP"),
                    rs.getString("OBJECT_SCHEMA"),
                    rs.getString("OBJECT_NAME"),
                    rs.getString("STATEMENT_TYPE"),
                    rs.getString("SQL_TEXT")
                });
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    public void LoadCombobox_UserName() throws ClassNotFoundException {

        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) Combobox_UserName.getModel();
        cbbModel.removeAllElements();
        Statement stmt = null;
        ResultSet rs = null;
        try {
            con = ConnectOracle.getConnecOracle();
            stmt = con.createStatement();
            String sql = "SELECT username FROM dba_users";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                String username = rs.getString("username");
                cbbModel.addElement(username);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public Manager() throws SQLException, ClassNotFoundException {
        initComponents();
//        getDataTable_SGA();
//        getDataTable_PGA();
//        getDataTable_PROCESS();
//        getDataTable_INSTANCE();
//        getDataTable_DATABASE();
//        getDataTable_DATAFILE();
//        getDataTable_CONTROLFILE();
//        getDataTable_SPFILE();
//        getDataText_SESSION();
//        getDataTable_SESSION();
//           getDataTable_AUDIT();

    }
    private void LB_PGAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_PGAMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_PGA();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(true);
        Panel_Session.setVisible(false);
        Panel_ControlFile.setVisible(false);
        Panel_Database.setVisible(false);
        Panel_Datafile.setVisible(false);
        Panel_Instance.setVisible(false);
        Panel_Process.setVisible(false);
        Panel_Sga.setVisible(false);
        Panel_SpFile.setVisible(false);
        Panel_Audit.setVisible(false);
    }//GEN-LAST:event_LB_PGAMouseClicked

    private void LB_SESSIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_SESSIONMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_SESSION();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            getDataText_SESSION();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(false);
        Panel_Session.setVisible(true);
        Panel_ControlFile.setVisible(false);
        Panel_Database.setVisible(false);
        Panel_Datafile.setVisible(false);
        Panel_Instance.setVisible(false);
        Panel_Process.setVisible(false);
        Panel_Sga.setVisible(false);
        Panel_SpFile.setVisible(false);
        Panel_Audit.setVisible(false);
    }//GEN-LAST:event_LB_SESSIONMouseClicked

    private void TBL_SESSIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_SESSIONMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) TBL_SESSION.getModel();
        String tblSid = tableModel.getValueAt(TBL_SESSION.getSelectedRow(), 0).toString();
        String tblSerial = tableModel.getValueAt(TBL_SESSION.getSelectedRow(), 1).toString();
        Txt_SID.setText(tblSid);
        Txt_SERIAL.setText(tblSerial);
    }//GEN-LAST:event_TBL_SESSIONMouseClicked

    private void Txt_SIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_SIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_SIDActionPerformed

    private void Txt_SERIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_SERIALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_SERIALActionPerformed

    private void HUY_SESSIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HUY_SESSIONActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) TBL_SESSION.getModel();
        if (TBL_SESSION.getSelectedRowCount() == 1) {
            String sid = Txt_SID.getText();
            String serial = Txt_SERIAL.getText();

            try {
//                String tk = Login.getDataUser.tenTk;
//                String mk = Login.getDataUser.mk;
                con = ConnectOracle.getConnecOracle();
                String sql = "ALTER SYSTEM KILL SESSION '" + sid + "," + serial + "'IMMEDIATE";
                stmt = con.createStatement();
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(new JFrame(), "Hủy session thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                // Đóng form thuộc session tương ứng
                closeFormBySessionID(sid);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(), e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if (rs != null) {
                        rs.close();
                    }
                    if (stmt != null) {
                        stmt.close();
                    }
                    if (con != null) {
                        con.close();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_HUY_SESSIONActionPerformed

    private void LB_SGAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_SGAMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_SGA();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(false);
        Panel_Session.setVisible(false);
        Panel_ControlFile.setVisible(false);
        Panel_Database.setVisible(false);
        Panel_Datafile.setVisible(false);
        Panel_Instance.setVisible(false);
        Panel_Process.setVisible(false);
        Panel_Sga.setVisible(true);
        Panel_SpFile.setVisible(false);
        Panel_Audit.setVisible(false);
    }//GEN-LAST:event_LB_SGAMouseClicked

    private void LB_PROCESSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_PROCESSMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_PROCESS();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(false);
        Panel_Session.setVisible(false);
        Panel_ControlFile.setVisible(false);
        Panel_Database.setVisible(false);
        Panel_Datafile.setVisible(false);
        Panel_Instance.setVisible(false);
        Panel_Process.setVisible(true);
        Panel_Sga.setVisible(false);
        Panel_SpFile.setVisible(false);
        Panel_Audit.setVisible(false);
    }//GEN-LAST:event_LB_PROCESSMouseClicked

    private void LB_INSTANCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_INSTANCEMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_INSTANCE();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(false);
        Panel_Session.setVisible(false);
        Panel_ControlFile.setVisible(false);
        Panel_Database.setVisible(false);
        Panel_Datafile.setVisible(false);
        Panel_Instance.setVisible(true);
        Panel_Process.setVisible(false);
        Panel_Sga.setVisible(false);
        Panel_SpFile.setVisible(false);
        Panel_Audit.setVisible(false);
    }//GEN-LAST:event_LB_INSTANCEMouseClicked

    private void LB_DATABASEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_DATABASEMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_DATABASE();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(false);
        Panel_Session.setVisible(false);
        Panel_ControlFile.setVisible(false);
        Panel_Database.setVisible(true);
        Panel_Datafile.setVisible(false);
        Panel_Instance.setVisible(false);
        Panel_Process.setVisible(false);
        Panel_Sga.setVisible(false);
        Panel_SpFile.setVisible(false);
        Panel_Audit.setVisible(false);
    }//GEN-LAST:event_LB_DATABASEMouseClicked

    private void LB_CONTROLFILEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_CONTROLFILEMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_CONTROLFILE();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(false);
        Panel_Session.setVisible(false);
        Panel_ControlFile.setVisible(true);
        Panel_Database.setVisible(false);
        Panel_Datafile.setVisible(false);
        Panel_Instance.setVisible(false);
        Panel_Process.setVisible(false);
        Panel_Sga.setVisible(false);
        Panel_SpFile.setVisible(false);
        Panel_Audit.setVisible(false);
    }//GEN-LAST:event_LB_CONTROLFILEMouseClicked

    private void LB_SPFILEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_SPFILEMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_SPFILE();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(false);
        Panel_Session.setVisible(false);
        Panel_ControlFile.setVisible(false);
        Panel_Database.setVisible(false);
        Panel_Datafile.setVisible(false);
        Panel_Instance.setVisible(false);
        Panel_Process.setVisible(false);
        Panel_Sga.setVisible(false);
        Panel_SpFile.setVisible(true);
        Panel_Audit.setVisible(false);
    }//GEN-LAST:event_LB_SPFILEMouseClicked

    private void LB_DATAFILEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_DATAFILEMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_DATAFILE();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(false);
        Panel_Session.setVisible(false);
        Panel_ControlFile.setVisible(false);
        Panel_Database.setVisible(false);
        Panel_Datafile.setVisible(true);
        Panel_Instance.setVisible(false);
        Panel_Process.setVisible(false);
        Panel_Sga.setVisible(false);
        Panel_SpFile.setVisible(false);
        Panel_Audit.setVisible(false);
    }//GEN-LAST:event_LB_DATAFILEMouseClicked

    private void LB_AUDITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_AUDITMouseClicked
        try {
            // TODO add your handling code here:
            getDataTable_AUDIT();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            LoadCombobox_UserName();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel_Pga.setVisible(false);
        Panel_Session.setVisible(false);
        Panel_ControlFile.setVisible(false);
        Panel_Database.setVisible(false);
        Panel_Datafile.setVisible(false);
        Panel_Instance.setVisible(false);
        Panel_Process.setVisible(false);
        Panel_Sga.setVisible(false);
        Panel_SpFile.setVisible(false);
        Panel_Audit.setVisible(true);

    }//GEN-LAST:event_LB_AUDITMouseClicked

    private void Button_LocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LocActionPerformed
        // TODO add your handling code here:
        String Item = (String) Combobox_UserName.getSelectedItem();
        try {
//            String tk = Login.getDataUser.tenTk;
//            String mk = Login.getDataUser.mk;
            con = ConnectOracle.getConnecOracle();
            String sql = "SELECT session_id,db_user,os_user,extended_timestamp,object_schema,object_name,statement_type,sql_text FROM dba_fga_audit_trail where db_user='" + Item + "'";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TBL_AUDIT.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getBigDecimal("SESSION_ID"),
                    rs.getString("DB_USER"),
                    rs.getString("OS_USER"),
                    rs.getTimestamp("EXTENDED_TIMESTAMP"),
                    rs.getString("OBJECT_SCHEMA"),
                    rs.getString("OBJECT_NAME"),
                    rs.getString("STATEMENT_TYPE"),
                    rs.getString("SQL_TEXT")
                });
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        int count = 0;
        Connection conn;
        Statement stmt1;
        ResultSet rs1;
        try {
//            String tk = Login.getDataUser.tenTk;
//            String mk = Login.getDataUser.mk;
            conn = ConnectOracle.getConnecOracle();
            String sql1 = "SELECT COUNT(*) AS TotalCount FROM dba_fga_audit_trail WHERE db_user = '"+Item+"'AND statement_type = 'SELECT'AND TRUNC(extended_timestamp) = TRUNC(SYSDATE)";
            stmt1 = conn.createStatement();
            rs1 = stmt1.executeQuery(sql1);

            if (rs1.next()) { // Di chuyển con trỏ của ResultSet
                count = rs1.getInt("TotalCount");                
            }
            if(count>3)
            {
                JOptionPane.showMessageDialog(new JFrame(), "Người dùng tên'"+Item+"'đã select nhiều hơn 3 lần trong ngày!", "Dialog", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_Button_LocActionPerformed
    private void btnDXMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDXMActionPerformed
        // TODO add your handling code here:
        try {
            String tk = Login.getDataUser.tenTk;
            boolean check = logoutUser(tk);
            if(check == true) {
                this.setVisible(false);
                Login lg = new Login();
                lg.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDXMActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Loc;
    private javax.swing.JComboBox<String> Combobox_UserName;
    private javax.swing.JButton HUY_SESSION;
    private javax.swing.JLabel LB_AUDIT;
    private javax.swing.JLabel LB_CONTROLFILE;
    private javax.swing.JLabel LB_DATABASE;
    private javax.swing.JLabel LB_DATAFILE;
    private javax.swing.JLabel LB_INSTANCE;
    private javax.swing.JLabel LB_PGA;
    private javax.swing.JLabel LB_PROCESS;
    private javax.swing.JLabel LB_SESSION;
    private javax.swing.JLabel LB_SGA;
    private javax.swing.JLabel LB_SPFILE;
    private javax.swing.JPanel Panel_Audit;
    private javax.swing.JPanel Panel_ControlFile;
    private javax.swing.JPanel Panel_Database;
    private javax.swing.JPanel Panel_Datafile;
    private javax.swing.JPanel Panel_Instance;
    private javax.swing.JPanel Panel_Pga;
    private javax.swing.JPanel Panel_Process;
    private javax.swing.JPanel Panel_Session;
    private javax.swing.JPanel Panel_Sga;
    private javax.swing.JPanel Panel_SpFile;
    private javax.swing.JTable TBL_AUDIT;
    private javax.swing.JTable TBL_CONTROLFILE;
    private javax.swing.JTable TBL_DATABASE;
    private javax.swing.JTable TBL_DATAFILE;
    private javax.swing.JTable TBL_INSTANCE;
    private javax.swing.JTable TBL_PGA;
    private javax.swing.JTable TBL_PROCESS;
    private javax.swing.JTable TBL_SESSION;
    private javax.swing.JTable TBL_SGA;
    private javax.swing.JTable TBL_SPFILE;
    private javax.swing.JTextField Txt_SERIAL;
    private javax.swing.JTextField Txt_SID;
    private javax.swing.JButton btnDXM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_session;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab11;
    private javax.swing.JPanel tab12;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab6;
    private javax.swing.JPanel tab7;
    private javax.swing.JPanel tab8;
    // End of variables declaration//GEN-END:variables

}
