/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Database.ConnectOracle;
import Database.GetConnect;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author ADMIN
 */
public class pnAllProfile extends javax.swing.JPanel {

    /**
     * Creates new form pnAllProfile
     */
    Connection con = GetConnect.getUserConnected();
    public void viewProfiles(JTable table) throws ClassNotFoundException {
        try {
            CallableStatement cstmt = con.prepareCall("{call p_get_profile(?)}");
            cstmt.registerOutParameter(1, OracleTypes.CURSOR); // 
            cstmt.execute();

            ResultSet rs = (ResultSet) cstmt.getObject(1);

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0); // Clear existing data
            String[] columnNames = {"Profile", "Resource Name", "Resource Type", "Limit"};
            model.setColumnIdentifiers(columnNames);

            // Populate the table model
            while (rs.next()) {
                String profile = rs.getString("PROFILE");
                String resourceName = rs.getString("RESOURCE_NAME");
                String resourceType = rs.getString("RESOURCE_TYPE");
                String limit = rs.getString("LIMIT");
                model.addRow(new Object[]{profile, resourceName, resourceType, limit});
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public pnAllProfile() throws ClassNotFoundException {
        initComponents();
        viewProfiles(tblProfile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfile = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tblProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProfile);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("TẤT CẢ PROFILE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProfile;
    // End of variables declaration//GEN-END:variables
}
