/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Database.ConnectOracle;
import View.Login.getDataUser;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author ADMIN
 */
public class pnProfile extends javax.swing.JPanel {

    /**
     * Creates new form pnProfile
     */
    public pnProfile() throws ClassNotFoundException {
        initComponents();
                //getDataUser.tenTk
        viewProfile("TEMPORARY_USER_PROFILE", tblProfile);
    }
     public static void viewProfile(String tk, JTable table) throws ClassNotFoundException {
        try {
            Connection conn = ConnectOracle.getConnecOracle();

            CallableStatement cstmt = conn.prepareCall("{call p_get_profile_u(?, ?)}");
            cstmt.setString(1, tk); 
            cstmt.registerOutParameter(2, OracleTypes.CURSOR); 


            cstmt.execute();

            ResultSet rs = (ResultSet)cstmt.getObject(2);

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0); // Clear existing data
            String[] columnNames = {"Profile", "Resource Name", "Resource Type", "Limit"};
            model.setColumnIdentifiers(columnNames);

            // Populate the table model
            while (rs.next()) {
                String profile = rs.getString("PROFILE");
                String resourceName = rs.getString("RESOURCE_NAME");
                String resourceType = rs.getString("RESOURCE_TYPE");
                String limit = rs.getString("LIMIT");
                model.addRow(new Object[]{profile, resourceName, resourceType, limit});
            }

            // Clean up
            rs.close();
            cstmt.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfile = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("THÔNG TIN PROFILE");

        tblProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProfile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProfile;
    // End of variables declaration//GEN-END:variables
}
