/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class pnPrUser extends javax.swing.JPanel {

    /**
     * Creates new form pnPrUser
     */
    private JPanel chillPn;
    public pnPrUser() {
        initComponents();
        try {
            chillPn = new pnUser();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnMain.removeAll();
        pnMain.add(chillPn);
        pnMain.repaint();
        pnMain.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAllPro = new javax.swing.JButton();
        btnAddProfile = new javax.swing.JButton();

        btnXem.setText("Xem Profile");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa thông tin");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        pnMain.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pnMain.add(jPanel1, "card2");

        btnAllPro.setText("Tất cả Profile");
        btnAllPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllProActionPerformed(evt);
            }
        });

        btnAddProfile.setText("Thêm Profile");
        btnAddProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAllPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXem)
                    .addComponent(btnAllPro)
                    .addComponent(btnAddProfile))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        chillPn = new pnFixUser();
        pnMain.removeAll();
        pnMain.add(chillPn);
        pnMain.repaint();
        pnMain.revalidate();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
        try {
            // TODO add your handling code here:
            chillPn = new pnProfile();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pnPrUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnMain.removeAll();
        pnMain.add(chillPn);
        pnMain.repaint();
        pnMain.revalidate();
    }//GEN-LAST:event_btnXemActionPerformed

    private void btnAllProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllProActionPerformed
        try {
            // TODO add your handling code here:
            chillPn = new pnAllProfile();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pnPrUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnMain.removeAll();
        pnMain.add(chillPn);
        pnMain.repaint();
        pnMain.revalidate();
    }//GEN-LAST:event_btnAllProActionPerformed

    private void btnAddProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProfileActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
            chillPn = new pnAddProfile();
        pnMain.removeAll();
        pnMain.add(chillPn);
        pnMain.repaint();
        pnMain.revalidate();
    }//GEN-LAST:event_btnAddProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProfile;
    private javax.swing.JButton btnAllPro;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
